# Generated by Django 5.2.9 on 2026-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentleadmodel',
            old_name='Source',
            new_name='source',
        ),
    ]
